name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hynek/setup-uv@v1
      - run: uv sync --dev
      - run: |
          uv run pulser kb overview > demo_output.txt
          cat demo_output.txt
      - uses: actions/upload-artifact@v4
        with: 
          name: demo-output
          path: demo_output.txt
